name: post-stroke-aphasia-risk-analysis-env
channels:
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - scipy
  - seaborn
  - ipykernel
  - jupyter
  - conda-forge::redshift_connector
  - make
  - pip
  - pip:
      - xgboost>=1.5.0
      - shap>=0.41.0
      - imbalanced-learn>=0.9.0
      - statsmodels>=0.13.0
